spring.application.name=bookmyshow-backend
spring.datasource.url=jdbc:postgresql://172.31.252.101:5432/bookMyShowDev
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

# Security
app.jwt.secret=djfl45!dnvkdEiwOsmvSdfjviwenvwGjo4w9vjwevn3432
app.jwt.expiration-ms=600000



server.port=8080

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

swagger.file.path=classpath:swagger.properties


