spring.application.name=bookmyshow-backend
#spring.datasource.url=jdbc:postgresql://localhost:5434/something
spring.datasource.url=jdbc:postgresql://localhost:5434/somthing
spring.datasource.username=postgres
spring.datasource.password=in2it@123

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Security
app.jwt.secret=djfl45!dnvkdEiwOsmvSdfjviwenvwGjo4w9vjwevn3432
app.jwt.expiration-ms=600000
server.port=8082