spring.application.name=bookmyshow-backend
<<<<<<< HEAD
spring.datasource.url=jdbc:postgresql://localhost:5434/BookMyShow
spring.datasource.username=postgres
spring.datasource.password=in2it@123
=======


spring.datasource.url=jdbc:postgresql://localhost:5432/BookMyShow
spring.datasource.username=myuser
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
>>>>>>> master
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update