# User Controller
user.getUserById=API to get User by Id
user.getUserByName=API to get Users by Name
user.getUserByUsername=API to get User by Username
user.getUserByEmail=API to get User by Email
user.getUserByRole=API to get Users by Role
user.getUserByPhone=API to get User by Phone
user.getAllUsers=API to fetch all Users
user.deleteUser=API to delete User by Id
user.updateUserRole=API to update User Role
user.validateUsername=API to validate Username

# Role Controller
role.getRoleById=API to get Role by Id
role.getRoleByName=API to get Role by Name
role.getAllRoles=API to fetch all Roles

# Auth Controller
auth.login=API to authenticate user and generate JWT token
auth.register=API to register a new user

# Event Controller
event.getPopularEvents=API to get top popular events by release date
event.getByCategoryEvent=API to get Event by Category