server.port=8080
server.servlet.context-path=/##BOOKMYSHOW##
spring.application.name=##BOOKMYSHOWSERVICE##
spring.datasource.url=jdbc:postgresql://##DB_IP##:##DB_PORT##/##DB_NAME##
spring.datasource.username=##DB_USER##
spring.datasource.password=##DB_PASS##
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none

spring.data.redis.host=##REDIS_HOST##
spring.data.redis.port=##REDIS_PORT##   
# Security
app.jwt.secret=##SECRET##
app.jwt.expiration-ms=##TTL##
swagger.file.path=classpath:swagger.properties

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
logging.level.org.springframework.data.redis=DEBUG
logging.level.io.lettuce.core=DEBUG
